###
GET http://localhost:3000/users/groups/5

###
GET http://localhost:3000/users/groups
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwdCI6MTY3ODIwNDkwOSwiaWF0IjoxNjc3MzQwOTA5fQ.cE_EG3od8CyI8jsgg5XSdd8RA9lS9ykRjWeC9DW633w