###
GET http://localhost:3000/users/groups/5

###
GET http://localhost:3000/users/groups/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwdCI6MTY3ODIwNDkwOSwiaWF0IjoxNjc3MzQwOTA5fQ.cE_EG3od8CyI8jsgg5XSdd8RA9lS9ykRjWeC9DW633w

###
GET http://localhost:3000/users/groups
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwdCI6MTY3ODIwNDkwOSwiaWF0IjoxNjc3MzQwOTA5fQ.cE_EG3od8CyI8jsgg5XSdd8RA9lS9ykRjWeC9DW633w

###
GET http://localhost:3000/users/groups/10/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwdCI6MTY3ODIwNDkwOSwiaWF0IjoxNjc3MzQwOTA5fQ.cE_EG3od8CyI8jsgg5XSdd8RA9lS9ykRjWeC9DW633w

###
POST http://localhost:3000/users/groups/new
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwdCI6MTY3ODM4ODA2NCwiaWF0IjoxNjc3NTI0MDY0fQ.iXld_o59M3nJMn7LrWFHhwEZbBDTFCmQ_jHaffy3Hfo
Content-Type: application/json

{
    "groupTitle": "Nuevo grupo"
}

###
POST http://localhost:3000/users/groups/14/addUser
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwdCI6MTY3ODQzOTIwMSwiaWF0IjoxNjc3NTc1MjAxfQ.b6jjC4252ILJmf1jZBwWrcXW4DSmIj1OBRdxrG0FfLw
Content-Type: application/json

{
    "userId": "11"
}

###
GET http://localhost:3000/users/groups/1/amounts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwdCI6MTY3ODIwNDkwOSwiaWF0IjoxNjc3MzQwOTA5fQ.cE_EG3od8CyI8jsgg5XSdd8RA9lS9ykRjWeC9DW633w

###
DELETE http://localhost:3000/users/groups/2/delete
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwdCI6MTY3ODIwNDkwOSwiaWF0IjoxNjc3MzQwOTA5fQ.cE_EG3od8CyI8jsgg5XSdd8RA9lS9ykRjWeC9DW633w