###
POST http://localhost:3000/users/groups/14/invitation
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwdCI6MTY3ODg3MzM1MSwiaWF0IjoxNjc4MDA5MzUxfQ.UvtyJX_oeXgBqCz0TUB7y_vH-bgJ3dDczC7FGZGByIM
Content-Type: application/json

{
    "userEmail" : "juanfer@terra.es"
}

###
GET http://localhost:3000/users/home/invitations
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZXhwdCI6MTY3ODg3OTcyMSwiaWF0IjoxNjc4MDE1NzIxfQ.d7fF8UrRI0o-OiVe2OG_PUk1bauvO9eGo7Q3fi5xRUc

###
PATCH  http://localhost:3000/users/home/invitations/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZXhwdCI6MTY3ODg3OTcyMSwiaWF0IjoxNjc4MDE1NzIxfQ.d7fF8UrRI0o-OiVe2OG_PUk1bauvO9eGo7Q3fi5xRUc

###
POST http://localhost:3000/users/home/invitations/2/accept
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZXhwdCI6MTY3ODg3OTcyMSwiaWF0IjoxNjc4MDE1NzIxfQ.d7fF8UrRI0o-OiVe2OG_PUk1bauvO9eGo7Q3fi5xRUc