###
GET http://localhost:3000/users/social
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwdCI6MTY3ODQzOTIwMSwiaWF0IjoxNjc3NTc1MjAxfQ.b6jjC4252ILJmf1jZBwWrcXW4DSmIj1OBRdxrG0FfLw