###
GET http://localhost:3000/users/home/9

###
GET http://localhost:3000/users/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwdCI6MTY3ODIwNDQxOCwiaWF0IjoxNjc3MzQwNDE4fQ.KdW5XWqlBQ0NUWC2zUpG7QMbuFFHeNSikqo-fx7mfzc

###
GET http://localhost:3000/users/home/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwdCI6MTY3ODIwNDQxOCwiaWF0IjoxNjc3MzQwNDE4fQ.KdW5XWqlBQ0NUWC2zUpG7QMbuFFHeNSikqo-fx7mfzc

###
POST http://localhost:3000/login/register
Content-Type: application/json

{
    "userName": "Manuel",
    "userSurname": "Jiménez",
    "userEmail": "manji@gmail.com",
    "userPhone": "765549821",
    "password": "porelmonte"
}

###
POST http://localhost:3000/login/
Content-Type: application/json

{
    "userEmail": "marmor@terra.es",
    "password": "lamartavacilona"
}

###
POST http://localhost:3000/login/
Content-Type: application/json

{
    "userEmail": "juanfer@terra.es",
    "password": "juanitojuan"
}